export default{
    "success":true,
    "data":{
        "meme":[
            {
                "id":"1",
                "name":"disaster_girl",
                "url":"https://cdn.wionews.com/sites/default/files/styles/story_page/public/2021/05/02/193478-disaster-girl-meme.jpg",
                "width":900,
                "height":900,
                "box_count":2
            },
            {
                "id":"2",
                "name":"jordan_crying",
                "url":"https://media.npr.org/assets/img/2016/03/29/ap_090911089838_sq-3271237f28995f6530d9634ff27228cae88e3440-s1100-c50.jpg",
                "width":900,
                "height":900,
                "box_count":3
            },
            {
                "id":"2",
                "name":"yah_baby",
                "url":"https://images.theconversation.com/files/38926/original/5cwx89t4-1389586191.jpg?ixlib=rb-1.1.0&q=45&auto=format&w=1200&h=1200.0&fit=crop",
                "width":900,
                "height":900,
                "box_count":4
            },
            {
                "id":"3",
                "name":"angry_face",
                "url":"https://image.shutterstock.com/image-vector/angry-face-looking-computer-vector-260nw-2027016299.jpg",
                "width":900,
                "height":900,
                "box_count":5
            },
            {
                "id":"4",
                "name":"money",
                "url":"https://i.imgflip.com/4za7t1.jpg",
                "width":900,
                "height":900,
                "box_count":2
            },
        ]
    }
}